name: file_digest_example
description: Demonstrates how to use the file_digest plugin.
publish_to: "none"

environment:
  sdk: ">=3.13.0 <4.0.0"

dependencies:
  cross_file: any
  flutter:
    sdk: flutter
  file_digest:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
