name: file_digest
description: Easily create digest hex for files
version: 0.0.5
homepage: https://github.com/DaPotatoMan/file_digest

topics:
  - file
  - digest

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  cross_file: ">=0.3.0 <1.0.0"
  crypto: ">=3.0.0 <4.0.0"
  web: ">=1.0.0 <2.0.0"

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - path: assets/worker.js
      platforms: [web]
