name: file_digest
description: Generate MD5, SHA-256, and SHA-512 digest hashes from files, byte data, or streams.
version: 0.0.5
homepage: https://github.com/DaPotatoMan/file_digest
repository: https://github.com/DaPotatoMan/file_digest
issue_tracker: https://github.com/DaPotatoMan/file_digest/issues

topics:
  - file
  - hash
  - checksum
  - md5
  - sha256

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  cross_file: ">=0.3.0 <1.0.0"
  crypto: ">=3.0.0 <4.0.0"
  web: ">=1.0.0 <2.0.0"

dev_dependencies:
  benchmark_harness: ^2.4.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - path: assets/worker.js
      platforms: [web]
